# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.api.legacy_api import LegacyApi


class TestLegacyApi(unittest.TestCase):
    """LegacyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LegacyApi()

    def tearDown(self) -> None:
        pass

    def test_deliveries_legacy_liveramp_deliveries_get(self) -> None:
        """Test case for deliveries_legacy_liveramp_deliveries_get

        Deliveries Legacy
        """
        pass

    def test_destinations_legacy_liveramp_destinations_get(self) -> None:
        """Test case for destinations_legacy_liveramp_destinations_get

        Destinations Legacy
        """
        pass

    def test_health_legacy_health_get(self) -> None:
        """Test case for health_legacy_health_get

        Health Legacy
        """
        pass

    def test_marketplace_detail_legacy_liveramp_marketplace_segments_detail_get(self) -> None:
        """Test case for marketplace_detail_legacy_liveramp_marketplace_segments_detail_get

        Marketplace Detail Legacy
        """
        pass

    def test_marketplace_segments_legacy_liveramp_marketplace_segments_get(self) -> None:
        """Test case for marketplace_segments_legacy_liveramp_marketplace_segments_get

        Marketplace Segments Legacy
        """
        pass

    def test_requested_segments_legacy_liveramp_requested_segments_post(self) -> None:
        """Test case for requested_segments_legacy_liveramp_requested_segments_post

        Requested Segments Legacy
        """
        pass

    def test_segment_statuses_legacy_liveramp_segment_statuses_get(self) -> None:
        """Test case for segment_statuses_legacy_liveramp_segment_statuses_get

        Segment Statuses Legacy
        """
        pass

    def test_segments_legacy_liveramp_segments_get(self) -> None:
        """Test case for segments_legacy_liveramp_segments_get

        Segments Legacy
        """
        pass


if __name__ == '__main__':
    unittest.main()
