# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.api.v1_api import V1Api


class TestV1Api(unittest.TestCase):
    """V1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = V1Api()

    def tearDown(self) -> None:
        pass

    def test_get_marketplace_segment_detail(self) -> None:
        """Test case for get_marketplace_segment_detail

        Marketplace Segments Detail
        """
        pass

    def test_get_segment_statuses(self) -> None:
        """Test case for get_segment_statuses

        List Segment Statuses
        """
        pass

    def test_health_v1_health_get(self) -> None:
        """Test case for health_v1_health_get

        Health
        """
        pass

    def test_list_deliveries(self) -> None:
        """Test case for list_deliveries

        Deliveries
        """
        pass

    def test_list_destinations(self) -> None:
        """Test case for list_destinations

        List Destinations
        """
        pass

    def test_list_first_party_segments(self) -> None:
        """Test case for list_first_party_segments

        List First Party Segments
        """
        pass

    def test_list_marketplace_segments(self) -> None:
        """Test case for list_marketplace_segments

        List Marketplace Segments
        """
        pass

    def test_ready_v1_ready_get(self) -> None:
        """Test case for ready_v1_ready_get

        Ready
        """
        pass

    def test_request_segments(self) -> None:
        """Test case for request_segments

        Request Segments For Activation
        """
        pass


if __name__ == '__main__':
    unittest.main()
