# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.marketplace_segment_list_response import MarketplaceSegmentListResponse

class TestMarketplaceSegmentListResponse(unittest.TestCase):
    """MarketplaceSegmentListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplaceSegmentListResponse:
        """Test MarketplaceSegmentListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplaceSegmentListResponse`
        """
        model = MarketplaceSegmentListResponse()
        if include_optional:
            return MarketplaceSegmentListResponse(
                segments = [
                    pulsepoint_liveramp.models.marketplace_segment.MarketplaceSegment(
                        id = '', 
                        name = '', 
                        provider = '', )
                    ],
                pagination = pulsepoint_liveramp.models.pagination.Pagination(
                    after = '', 
                    total = 56, )
            )
        else:
            return MarketplaceSegmentListResponse(
                segments = [
                    pulsepoint_liveramp.models.marketplace_segment.MarketplaceSegment(
                        id = '', 
                        name = '', 
                        provider = '', )
                    ],
                pagination = pulsepoint_liveramp.models.pagination.Pagination(
                    after = '', 
                    total = 56, ),
        )
        """

    def testMarketplaceSegmentListResponse(self):
        """Test MarketplaceSegmentListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
