# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.marketplace_segment_detail import MarketplaceSegmentDetail

class TestMarketplaceSegmentDetail(unittest.TestCase):
    """MarketplaceSegmentDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplaceSegmentDetail:
        """Test MarketplaceSegmentDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplaceSegmentDetail`
        """
        model = MarketplaceSegmentDetail()
        if include_optional:
            return MarketplaceSegmentDetail(
                segment_id = 56,
                name = '',
                description = '',
                category = '',
                country_codes = [
                    ''
                    ],
                currency_codes = [
                    ''
                    ],
                identifier_types = [
                    ''
                    ]
            )
        else:
            return MarketplaceSegmentDetail(
                segment_id = 56,
        )
        """

    def testMarketplaceSegmentDetail(self):
        """Test MarketplaceSegmentDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
