# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.marketplace_segment_detail_response import MarketplaceSegmentDetailResponse

class TestMarketplaceSegmentDetailResponse(unittest.TestCase):
    """MarketplaceSegmentDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplaceSegmentDetailResponse:
        """Test MarketplaceSegmentDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplaceSegmentDetailResponse`
        """
        model = MarketplaceSegmentDetailResponse()
        if include_optional:
            return MarketplaceSegmentDetailResponse(
                segments = [
                    pulsepoint_liveramp.models.marketplace_segment_detail.MarketplaceSegmentDetail(
                        segment_id = 56, 
                        name = '', 
                        description = '', 
                        category = '', 
                        country_codes = [
                            ''
                            ], 
                        currency_codes = [
                            ''
                            ], 
                        identifier_types = [
                            ''
                            ], )
                    ],
                pagination = pulsepoint_liveramp.models.pagination.Pagination(
                    after = '', 
                    total = 56, )
            )
        else:
            return MarketplaceSegmentDetailResponse(
                segments = [
                    pulsepoint_liveramp.models.marketplace_segment_detail.MarketplaceSegmentDetail(
                        segment_id = 56, 
                        name = '', 
                        description = '', 
                        category = '', 
                        country_codes = [
                            ''
                            ], 
                        currency_codes = [
                            ''
                            ], 
                        identifier_types = [
                            ''
                            ], )
                    ],
                pagination = pulsepoint_liveramp.models.pagination.Pagination(
                    after = '', 
                    total = 56, ),
        )
        """

    def testMarketplaceSegmentDetailResponse(self):
        """Test MarketplaceSegmentDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
