# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.country_code import CountryCode

class TestCountryCode(unittest.TestCase):
    """CountryCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountryCode(self):
        """Test CountryCode"""
        # inst = CountryCode()

if __name__ == '__main__':
    unittest.main()
