# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.delivery import Delivery

class TestDelivery(unittest.TestCase):
    """Delivery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Delivery:
        """Test Delivery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Delivery`
        """
        model = Delivery()
        if include_optional:
            return Delivery(
                delivery_id = '',
                segment_id = 56,
                destination_id = '',
                status = '',
                created_at = ''
            )
        else:
            return Delivery(
        )
        """

    def testDelivery(self):
        """Test Delivery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
