# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.delivery_list_response import DeliveryListResponse

class TestDeliveryListResponse(unittest.TestCase):
    """DeliveryListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveryListResponse:
        """Test DeliveryListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliveryListResponse`
        """
        model = DeliveryListResponse()
        if include_optional:
            return DeliveryListResponse(
                deliveries = [
                    pulsepoint_liveramp.models.delivery.Delivery(
                        delivery_id = '', 
                        segment_id = 56, 
                        destination_id = '', 
                        status = '', 
                        created_at = '', )
                    ],
                pagination = pulsepoint_liveramp.models.pagination.Pagination(
                    after = '', 
                    total = 56, )
            )
        else:
            return DeliveryListResponse(
                deliveries = [
                    pulsepoint_liveramp.models.delivery.Delivery(
                        delivery_id = '', 
                        segment_id = 56, 
                        destination_id = '', 
                        status = '', 
                        created_at = '', )
                    ],
                pagination = pulsepoint_liveramp.models.pagination.Pagination(
                    after = '', 
                    total = 56, ),
        )
        """

    def testDeliveryListResponse(self):
        """Test DeliveryListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
