# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.currency_code import CurrencyCode

class TestCurrencyCode(unittest.TestCase):
    """CurrencyCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrencyCode(self):
        """Test CurrencyCode"""
        # inst = CurrencyCode()

if __name__ == '__main__':
    unittest.main()
