# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.segment_type import SegmentType

class TestSegmentType(unittest.TestCase):
    """SegmentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSegmentType(self):
        """Test SegmentType"""
        # inst = SegmentType()

if __name__ == '__main__':
    unittest.main()
