# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.segment_status_list_response import SegmentStatusListResponse

class TestSegmentStatusListResponse(unittest.TestCase):
    """SegmentStatusListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SegmentStatusListResponse:
        """Test SegmentStatusListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SegmentStatusListResponse`
        """
        model = SegmentStatusListResponse()
        if include_optional:
            return SegmentStatusListResponse(
                statuses = [
                    pulsepoint_liveramp.models.segment_status.SegmentStatus(
                        segment_id = 56, 
                        destination_id = 56, 
                        status = '', 
                        last_updated = '', )
                    ],
                pagination = pulsepoint_liveramp.models.pagination.Pagination(
                    after = '', 
                    total = 56, )
            )
        else:
            return SegmentStatusListResponse(
                statuses = [
                    pulsepoint_liveramp.models.segment_status.SegmentStatus(
                        segment_id = 56, 
                        destination_id = 56, 
                        status = '', 
                        last_updated = '', )
                    ],
                pagination = pulsepoint_liveramp.models.pagination.Pagination(
                    after = '', 
                    total = 56, ),
        )
        """

    def testSegmentStatusListResponse(self):
        """Test SegmentStatusListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
