# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.api.v1_api import V1Api


class TestV1Api(unittest.TestCase):
    """V1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = V1Api()

    def tearDown(self) -> None:
        pass

    def test_deliveries_v1_liveramp_deliveries_get(self) -> None:
        """Test case for deliveries_v1_liveramp_deliveries_get

        Deliveries
        """
        pass

    def test_health_v1_health_get(self) -> None:
        """Test case for health_v1_health_get

        Health
        """
        pass

    def test_list_destinations_v1_liveramp_destinations_get(self) -> None:
        """Test case for list_destinations_v1_liveramp_destinations_get

        List Destinations
        """
        pass

    def test_list_first_party_segments_v1_liveramp_segments_get(self) -> None:
        """Test case for list_first_party_segments_v1_liveramp_segments_get

        List First Party Segments
        """
        pass

    def test_list_marketplace_segments_v1_liveramp_marketplace_segments_get(self) -> None:
        """Test case for list_marketplace_segments_v1_liveramp_marketplace_segments_get

        List Marketplace Segments
        """
        pass

    def test_list_segment_statuses_v1_liveramp_segment_statuses_get(self) -> None:
        """Test case for list_segment_statuses_v1_liveramp_segment_statuses_get

        List Segment Statuses
        """
        pass

    def test_marketplace_segments_detail_v1_liveramp_marketplace_segments_detail_get(self) -> None:
        """Test case for marketplace_segments_detail_v1_liveramp_marketplace_segments_detail_get

        Marketplace Segments Detail
        """
        pass

    def test_ready_v1_ready_get(self) -> None:
        """Test case for ready_v1_ready_get

        Ready
        """
        pass

    def test_request_segments_for_activation_v1_liveramp_requested_segments_post(self) -> None:
        """Test case for request_segments_for_activation_v1_liveramp_requested_segments_post

        Request Segments For Activation
        """
        pass


if __name__ == '__main__':
    unittest.main()
