# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.marketplace_pricing import MarketplacePricing

class TestMarketplacePricing(unittest.TestCase):
    """MarketplacePricing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplacePricing:
        """Test MarketplacePricing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplacePricing`
        """
        model = MarketplacePricing()
        if include_optional:
            return MarketplacePricing(
                use_case = '',
                currency_code = '',
                amount = 56,
                unit = ''
            )
        else:
            return MarketplacePricing(
                use_case = '',
        )
        """

    def testMarketplacePricing(self):
        """Test MarketplacePricing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
