# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pulsepoint_liveramp.models.requested_segments_request import RequestedSegmentsRequest

class TestRequestedSegmentsRequest(unittest.TestCase):
    """RequestedSegmentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestedSegmentsRequest:
        """Test RequestedSegmentsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestedSegmentsRequest`
        """
        model = RequestedSegmentsRequest()
        if include_optional:
            return RequestedSegmentsRequest(
                segments = [
                    pulsepoint_liveramp.models.requested_segment_input.RequestedSegmentInput(
                        segment_id = 56, 
                        destination_id = 56, 
                        identifier_type = '', )
                    ]
            )
        else:
            return RequestedSegmentsRequest(
                segments = [
                    pulsepoint_liveramp.models.requested_segment_input.RequestedSegmentInput(
                        segment_id = 56, 
                        destination_id = 56, 
                        identifier_type = '', )
                    ],
        )
        """

    def testRequestedSegmentsRequest(self):
        """Test RequestedSegmentsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
