# coding: utf-8

"""
    PulsePoint LiveRamp Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pulsepoint_liveramp.models.marketplace_pricing import MarketplacePricing
from typing import Optional, Set
from typing_extensions import Self

class MarketplaceSegmentDetail(BaseModel):
    """
    MarketplaceSegmentDetail
    """ # noqa: E501
    segment_id: Optional[StrictInt]
    name: Optional[StrictStr]
    description: Optional[StrictStr]
    category: Optional[StrictStr]
    country_codes: Optional[List[StrictStr]]
    currency_codes: Optional[List[StrictStr]]
    identifier_types: Optional[List[StrictStr]]
    pricing: Optional[List[MarketplacePricing]] = None
    __properties: ClassVar[List[str]] = ["segment_id", "name", "description", "category", "country_codes", "currency_codes", "identifier_types", "pricing"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketplaceSegmentDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pricing (list)
        _items = []
        if self.pricing:
            for _item_pricing in self.pricing:
                if _item_pricing:
                    _items.append(_item_pricing.to_dict())
            _dict['pricing'] = _items
        # set to None if segment_id (nullable) is None
        # and model_fields_set contains the field
        if self.segment_id is None and "segment_id" in self.model_fields_set:
            _dict['segment_id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict['category'] = None

        # set to None if country_codes (nullable) is None
        # and model_fields_set contains the field
        if self.country_codes is None and "country_codes" in self.model_fields_set:
            _dict['country_codes'] = None

        # set to None if currency_codes (nullable) is None
        # and model_fields_set contains the field
        if self.currency_codes is None and "currency_codes" in self.model_fields_set:
            _dict['currency_codes'] = None

        # set to None if identifier_types (nullable) is None
        # and model_fields_set contains the field
        if self.identifier_types is None and "identifier_types" in self.model_fields_set:
            _dict['identifier_types'] = None

        # set to None if pricing (nullable) is None
        # and model_fields_set contains the field
        if self.pricing is None and "pricing" in self.model_fields_set:
            _dict['pricing'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketplaceSegmentDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "segment_id": obj.get("segment_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "category": obj.get("category"),
            "country_codes": obj.get("country_codes"),
            "currency_codes": obj.get("currency_codes"),
            "identifier_types": obj.get("identifier_types"),
            "pricing": [MarketplacePricing.from_dict(_item) for _item in obj["pricing"]] if obj.get("pricing") is not None else None
        })
        return _obj


