/* tslint:disable */
/* eslint-disable */
/**
 * PulsePoint LiveRamp Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DeliveriesLegacyLiverampDeliveriesGetRequest {
    integrationConnectionID: string;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface DestinationsLegacyLiverampDestinationsGetRequest {
    limit?: number;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface HealthLegacyHealthGetRequest {
    xPPAPIKey?: string | null;
}

export interface MarketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGetRequest {
    ids: Array<number>;
    limit?: number;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface MarketplaceSegmentsLegacyLiverampMarketplaceSegmentsGetRequest {
    limit?: number;
    countryCodes?: Array<string> | null;
    currencyCodes?: Array<string> | null;
    identifierType?: Array<string> | null;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface RequestedSegmentsLegacyLiverampRequestedSegmentsPostRequest {
    requestBody: Array<{ [key: string]: any; }>;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface SegmentStatusesLegacyLiverampSegmentStatusesGetRequest {
    segmentIDs: Array<number>;
    segmentType?: string;
    limit?: number;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface SegmentsLegacyLiverampSegmentsGetRequest {
    limit?: number;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

/**
 * 
 */
export class LegacyApi extends runtime.BaseAPI {

    /**
     * Creates request options for deliveriesLegacyLiverampDeliveriesGet without sending the request
     * @deprecated
     */
    async deliveriesLegacyLiverampDeliveriesGetRequestOpts(requestParameters: DeliveriesLegacyLiverampDeliveriesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationConnectionID'] == null) {
            throw new runtime.RequiredError(
                'integrationConnectionID',
                'Required parameter "integrationConnectionID" was null or undefined when calling deliveriesLegacyLiverampDeliveriesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['integrationConnectionID'] != null) {
            queryParameters['integrationConnectionID'] = requestParameters['integrationConnectionID'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/liveramp/deliveries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deliveries Legacy
     * @deprecated
     */
    async deliveriesLegacyLiverampDeliveriesGetRaw(requestParameters: DeliveriesLegacyLiverampDeliveriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deliveriesLegacyLiverampDeliveriesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Deliveries Legacy
     * @deprecated
     */
    async deliveriesLegacyLiverampDeliveriesGet(requestParameters: DeliveriesLegacyLiverampDeliveriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deliveriesLegacyLiverampDeliveriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for destinationsLegacyLiverampDestinationsGet without sending the request
     * @deprecated
     */
    async destinationsLegacyLiverampDestinationsGetRequestOpts(requestParameters: DestinationsLegacyLiverampDestinationsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/liveramp/destinations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Destinations Legacy
     * @deprecated
     */
    async destinationsLegacyLiverampDestinationsGetRaw(requestParameters: DestinationsLegacyLiverampDestinationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.destinationsLegacyLiverampDestinationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Destinations Legacy
     * @deprecated
     */
    async destinationsLegacyLiverampDestinationsGet(requestParameters: DestinationsLegacyLiverampDestinationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.destinationsLegacyLiverampDestinationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthLegacyHealthGet without sending the request
     * @deprecated
     */
    async healthLegacyHealthGetRequestOpts(requestParameters: HealthLegacyHealthGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Health Legacy
     * @deprecated
     */
    async healthLegacyHealthGetRaw(requestParameters: HealthLegacyHealthGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.healthLegacyHealthGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Health Legacy
     * @deprecated
     */
    async healthLegacyHealthGet(requestParameters: HealthLegacyHealthGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.healthLegacyHealthGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for marketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGet without sending the request
     * @deprecated
     */
    async marketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGetRequestOpts(requestParameters: MarketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ids'] == null) {
            throw new runtime.RequiredError(
                'ids',
                'Required parameter "ids" was null or undefined when calling marketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/liveramp/marketplace/segments/detail`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marketplace Detail Legacy
     * @deprecated
     */
    async marketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGetRaw(requestParameters: MarketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.marketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Marketplace Detail Legacy
     * @deprecated
     */
    async marketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGet(requestParameters: MarketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.marketplaceDetailLegacyLiverampMarketplaceSegmentsDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for marketplaceSegmentsLegacyLiverampMarketplaceSegmentsGet without sending the request
     * @deprecated
     */
    async marketplaceSegmentsLegacyLiverampMarketplaceSegmentsGetRequestOpts(requestParameters: MarketplaceSegmentsLegacyLiverampMarketplaceSegmentsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['countryCodes'] != null) {
            queryParameters['countryCodes'] = requestParameters['countryCodes'];
        }

        if (requestParameters['currencyCodes'] != null) {
            queryParameters['currencyCodes'] = requestParameters['currencyCodes'];
        }

        if (requestParameters['identifierType'] != null) {
            queryParameters['identifierType'] = requestParameters['identifierType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/liveramp/marketplace/segments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marketplace Segments Legacy
     * @deprecated
     */
    async marketplaceSegmentsLegacyLiverampMarketplaceSegmentsGetRaw(requestParameters: MarketplaceSegmentsLegacyLiverampMarketplaceSegmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.marketplaceSegmentsLegacyLiverampMarketplaceSegmentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Marketplace Segments Legacy
     * @deprecated
     */
    async marketplaceSegmentsLegacyLiverampMarketplaceSegmentsGet(requestParameters: MarketplaceSegmentsLegacyLiverampMarketplaceSegmentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.marketplaceSegmentsLegacyLiverampMarketplaceSegmentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestedSegmentsLegacyLiverampRequestedSegmentsPost without sending the request
     * @deprecated
     */
    async requestedSegmentsLegacyLiverampRequestedSegmentsPostRequestOpts(requestParameters: RequestedSegmentsLegacyLiverampRequestedSegmentsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling requestedSegmentsLegacyLiverampRequestedSegmentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/liveramp/requested-segments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Requested Segments Legacy
     * @deprecated
     */
    async requestedSegmentsLegacyLiverampRequestedSegmentsPostRaw(requestParameters: RequestedSegmentsLegacyLiverampRequestedSegmentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.requestedSegmentsLegacyLiverampRequestedSegmentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Requested Segments Legacy
     * @deprecated
     */
    async requestedSegmentsLegacyLiverampRequestedSegmentsPost(requestParameters: RequestedSegmentsLegacyLiverampRequestedSegmentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.requestedSegmentsLegacyLiverampRequestedSegmentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for segmentStatusesLegacyLiverampSegmentStatusesGet without sending the request
     * @deprecated
     */
    async segmentStatusesLegacyLiverampSegmentStatusesGetRequestOpts(requestParameters: SegmentStatusesLegacyLiverampSegmentStatusesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['segmentIDs'] == null) {
            throw new runtime.RequiredError(
                'segmentIDs',
                'Required parameter "segmentIDs" was null or undefined when calling segmentStatusesLegacyLiverampSegmentStatusesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['segmentIDs'] != null) {
            queryParameters['segmentIDs'] = requestParameters['segmentIDs'];
        }

        if (requestParameters['segmentType'] != null) {
            queryParameters['segmentType'] = requestParameters['segmentType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/liveramp/segment-statuses`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Segment Statuses Legacy
     * @deprecated
     */
    async segmentStatusesLegacyLiverampSegmentStatusesGetRaw(requestParameters: SegmentStatusesLegacyLiverampSegmentStatusesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.segmentStatusesLegacyLiverampSegmentStatusesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Segment Statuses Legacy
     * @deprecated
     */
    async segmentStatusesLegacyLiverampSegmentStatusesGet(requestParameters: SegmentStatusesLegacyLiverampSegmentStatusesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.segmentStatusesLegacyLiverampSegmentStatusesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for segmentsLegacyLiverampSegmentsGet without sending the request
     * @deprecated
     */
    async segmentsLegacyLiverampSegmentsGetRequestOpts(requestParameters: SegmentsLegacyLiverampSegmentsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/liveramp/segments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Segments Legacy
     * @deprecated
     */
    async segmentsLegacyLiverampSegmentsGetRaw(requestParameters: SegmentsLegacyLiverampSegmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.segmentsLegacyLiverampSegmentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Segments Legacy
     * @deprecated
     */
    async segmentsLegacyLiverampSegmentsGet(requestParameters: SegmentsLegacyLiverampSegmentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.segmentsLegacyLiverampSegmentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
