/* tslint:disable */
/* eslint-disable */
/**
 * PulsePoint LiveRamp Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DeliveriesV1LiverampDeliveriesGetRequest {
    integrationConnectionID: string;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface HealthV1HealthGetRequest {
    xPPAPIKey?: string | null;
}

export interface ListDestinationsV1LiverampDestinationsGetRequest {
    limit?: number;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface ListFirstPartySegmentsV1LiverampSegmentsGetRequest {
    limit?: number;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface ListMarketplaceSegmentsV1LiverampMarketplaceSegmentsGetRequest {
    limit?: number;
    countryCodes?: Array<string> | null;
    currencyCodes?: Array<string> | null;
    identifierType?: Array<string> | null;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface MarketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGetRequest {
    ids: Array<number>;
    limit?: number;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface RequestSegmentsForActivationV1LiverampRequestedSegmentsPostRequest {
    requestBody: Array<{ [key: string]: any; }>;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

export interface SegmentStatusesV1LiverampSegmentStatusesGetRequest {
    segmentIDs: Array<number>;
    segmentType?: string;
    limit?: number;
    xLROrgId?: string | null;
    xPPAPIKey?: string | null;
}

/**
 * 
 */
export class V1Api extends runtime.BaseAPI {

    /**
     * Creates request options for deliveriesV1LiverampDeliveriesGet without sending the request
     */
    async deliveriesV1LiverampDeliveriesGetRequestOpts(requestParameters: DeliveriesV1LiverampDeliveriesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationConnectionID'] == null) {
            throw new runtime.RequiredError(
                'integrationConnectionID',
                'Required parameter "integrationConnectionID" was null or undefined when calling deliveriesV1LiverampDeliveriesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['integrationConnectionID'] != null) {
            queryParameters['integrationConnectionID'] = requestParameters['integrationConnectionID'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/v1/liveramp/deliveries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deliveries
     */
    async deliveriesV1LiverampDeliveriesGetRaw(requestParameters: DeliveriesV1LiverampDeliveriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deliveriesV1LiverampDeliveriesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Deliveries
     */
    async deliveriesV1LiverampDeliveriesGet(requestParameters: DeliveriesV1LiverampDeliveriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deliveriesV1LiverampDeliveriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthV1HealthGet without sending the request
     */
    async healthV1HealthGetRequestOpts(requestParameters: HealthV1HealthGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/v1/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Health
     */
    async healthV1HealthGetRaw(requestParameters: HealthV1HealthGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.healthV1HealthGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Health
     */
    async healthV1HealthGet(requestParameters: HealthV1HealthGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.healthV1HealthGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDestinationsV1LiverampDestinationsGet without sending the request
     */
    async listDestinationsV1LiverampDestinationsGetRequestOpts(requestParameters: ListDestinationsV1LiverampDestinationsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/v1/liveramp/destinations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Destinations
     */
    async listDestinationsV1LiverampDestinationsGetRaw(requestParameters: ListDestinationsV1LiverampDestinationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listDestinationsV1LiverampDestinationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Destinations
     */
    async listDestinationsV1LiverampDestinationsGet(requestParameters: ListDestinationsV1LiverampDestinationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listDestinationsV1LiverampDestinationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFirstPartySegmentsV1LiverampSegmentsGet without sending the request
     */
    async listFirstPartySegmentsV1LiverampSegmentsGetRequestOpts(requestParameters: ListFirstPartySegmentsV1LiverampSegmentsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/v1/liveramp/segments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List First Party Segments
     */
    async listFirstPartySegmentsV1LiverampSegmentsGetRaw(requestParameters: ListFirstPartySegmentsV1LiverampSegmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listFirstPartySegmentsV1LiverampSegmentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List First Party Segments
     */
    async listFirstPartySegmentsV1LiverampSegmentsGet(requestParameters: ListFirstPartySegmentsV1LiverampSegmentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listFirstPartySegmentsV1LiverampSegmentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMarketplaceSegmentsV1LiverampMarketplaceSegmentsGet without sending the request
     */
    async listMarketplaceSegmentsV1LiverampMarketplaceSegmentsGetRequestOpts(requestParameters: ListMarketplaceSegmentsV1LiverampMarketplaceSegmentsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['countryCodes'] != null) {
            queryParameters['countryCodes'] = requestParameters['countryCodes'];
        }

        if (requestParameters['currencyCodes'] != null) {
            queryParameters['currencyCodes'] = requestParameters['currencyCodes'];
        }

        if (requestParameters['identifierType'] != null) {
            queryParameters['identifierType'] = requestParameters['identifierType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/v1/liveramp/marketplace/segments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Marketplace Segments
     */
    async listMarketplaceSegmentsV1LiverampMarketplaceSegmentsGetRaw(requestParameters: ListMarketplaceSegmentsV1LiverampMarketplaceSegmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listMarketplaceSegmentsV1LiverampMarketplaceSegmentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Marketplace Segments
     */
    async listMarketplaceSegmentsV1LiverampMarketplaceSegmentsGet(requestParameters: ListMarketplaceSegmentsV1LiverampMarketplaceSegmentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listMarketplaceSegmentsV1LiverampMarketplaceSegmentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for marketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGet without sending the request
     */
    async marketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGetRequestOpts(requestParameters: MarketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ids'] == null) {
            throw new runtime.RequiredError(
                'ids',
                'Required parameter "ids" was null or undefined when calling marketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/v1/liveramp/marketplace/segments/detail`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marketplace Segments Detail
     */
    async marketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGetRaw(requestParameters: MarketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.marketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Marketplace Segments Detail
     */
    async marketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGet(requestParameters: MarketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.marketplaceSegmentsDetailV1LiverampMarketplaceSegmentsDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestSegmentsForActivationV1LiverampRequestedSegmentsPost without sending the request
     */
    async requestSegmentsForActivationV1LiverampRequestedSegmentsPostRequestOpts(requestParameters: RequestSegmentsForActivationV1LiverampRequestedSegmentsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling requestSegmentsForActivationV1LiverampRequestedSegmentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/v1/liveramp/requested-segments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Request Segments For Activation
     */
    async requestSegmentsForActivationV1LiverampRequestedSegmentsPostRaw(requestParameters: RequestSegmentsForActivationV1LiverampRequestedSegmentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.requestSegmentsForActivationV1LiverampRequestedSegmentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Request Segments For Activation
     */
    async requestSegmentsForActivationV1LiverampRequestedSegmentsPost(requestParameters: RequestSegmentsForActivationV1LiverampRequestedSegmentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.requestSegmentsForActivationV1LiverampRequestedSegmentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for segmentStatusesV1LiverampSegmentStatusesGet without sending the request
     */
    async segmentStatusesV1LiverampSegmentStatusesGetRequestOpts(requestParameters: SegmentStatusesV1LiverampSegmentStatusesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['segmentIDs'] == null) {
            throw new runtime.RequiredError(
                'segmentIDs',
                'Required parameter "segmentIDs" was null or undefined when calling segmentStatusesV1LiverampSegmentStatusesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['segmentIDs'] != null) {
            queryParameters['segmentIDs'] = requestParameters['segmentIDs'];
        }

        if (requestParameters['segmentType'] != null) {
            queryParameters['segmentType'] = requestParameters['segmentType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLROrgId'] != null) {
            headerParameters['X-LR-Org-Id'] = String(requestParameters['xLROrgId']);
        }

        if (requestParameters['xPPAPIKey'] != null) {
            headerParameters['X-PP-API-Key'] = String(requestParameters['xPPAPIKey']);
        }


        let urlPath = `/v1/liveramp/segment-statuses`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Segment Statuses
     */
    async segmentStatusesV1LiverampSegmentStatusesGetRaw(requestParameters: SegmentStatusesV1LiverampSegmentStatusesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.segmentStatusesV1LiverampSegmentStatusesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Segment Statuses
     */
    async segmentStatusesV1LiverampSegmentStatusesGet(requestParameters: SegmentStatusesV1LiverampSegmentStatusesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.segmentStatusesV1LiverampSegmentStatusesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
